version: "2"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        restart: always
        ports: 
            - 5672:5672
            - 15672:15672
        volumes: 
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        environment: 
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=password
        networks:
            - abc-networks

    publisher_service:
        build:
            - ./services/publisher/
        container_name: publisher_service
        restart: always
        ports: 
            - 8000:80
        volumes:
            - ./dados:/var/lib/python
        depends_on:
            - rabbitmq
        networks:
            - abc-networks

    consumer_service:
        build:
            - ./services/consumer/
        container_name: consumer_service
        restart: always
        volumes:
            - ./dados:/var/lib/python
        depends_on:
            - rabbitmq
        networks:
            - abc-networks

networks:
    abc-networks:
        driver: bridge
